# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
  - name: location
    type: string
    displayName: 'Azure Region'
    default: 'Australia East'
    values:
      - 'Australia East'
      - 'Australia SouthEast'
  - name: solutionName
    type: string
    displayName: 'Solution Name'
    default: 'toylaunch'
    
trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: fta-live-iac-ci
      trigger: true

pool:
  vmImage: 'ubuntu-latest'
      
stages:
  - template: templates/iac_release.yaml
    parameters:
      location: '${{ parameters.location }}'
      environment: 'nonprod'
      name: '${{ parameters.solutionName }}'

  - template: templates/app_release.yml
    parameters:
      environment: 'nonprod'
      name: '${{ parameters.solutionName }}'

  - template: templates/iac_release.yaml
    parameters:
      location: '${{ parameters.location }}'
      environment: 'prod'
      name: '${{ parameters.solutionName }}'
      
  - template: templates/app_release.yml
    parameters:
      environment: 'prod'
      name: '${{ parameters.solutionName }}'

