trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureAppServiceManage@0
    inputs:
      azureSubscription: 'azure_service_connection'
      Action: 'Swap Slots'
      WebAppName: '$(app_service_name)'
      ResourceGroupName: '$(resource_group)'
      SourceSlot: 'test'