# This is a basic workflow to help you get started with Actions

name: PR-Helper

# Controls when the action will run. 
on:
  pull_request:
    branches:
      - master
  pull_request_review:
    branches:
      - master
  issue_comment:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run PR Helper
        id: runprhelper
        uses: Matticusau/pr-helper@v1.2.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          enable-prmerge-automation: true
          enable-prcomment-automation: true
          enable-prlabel-automation: true
          enable-prreviewer-frontmatter: false
          enable-welcomemessage: true
          welcome-message: "Thanks for opening an issue! Make sure you've followed CONTRIBUTING.md."
          prmerge-requireallchecks: true
          prmerge-requirereviewcount: 1
          prmerge-method: 'merge'
          prlabel-ready: 'pr-ready'
          prlabel-reviewrequired: 'review-required'
          prlabel-automerge: 'auto-merge'
